version: '3.9'

services:
  db:
    image: postgres:15
    container_name: cloud_file_storage_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: vlad
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: cloud_file_storage_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: cloudfilestorage
      MINIO_ROOT_PASSWORD: cloudfilestorage
      MINIO_DEFAULT_BUCKETS: files
    command: server /data --console-address :9090
    ports:
      - "9000:9000"
      - "9090:9090"

volumes:
  minio-data: