version: '3.9'

services:
  db:
    image: postgres:15
    container_name: cloud_file_storage_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: vlad
    ports:
      - "5432:5432"