spring.application.name: cloud_file_storage

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: vlad
    password: vlad
  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml