spring.application.name: cloud_file_storage

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: vlad
    password: vlad
  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

minio:
  url: http://localhost:9000
  credentials:
    user: cloudfilestorage
    password: cloudfilestorage
  bucket:
    name: disk